version: '3'
services:
  python3:
    build: .
    image: python3/python3 
    restart: unless-stopped
#    ports:
#     - "8888:8888"
    volumes:
     - ./src:/home/src
    command: python hello.py 
